---
title: "little_library_analysis_viz"
format: html
editor: visual
---

```{r}

library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(here)
library(lubridate)
library(cori.charts)
library(stringr)

sysfonts::font_add_google("Lato")
showtext::showtext_auto()
showtext::showtext_opts(dpi = 300)

chart_color <- "#8856a7"

i_am("scripts/little_library_analysis_viz.qmd")

```

```{r}

dta_raw <- readr::read_csv(here("data/little_libraries_books_2025_06_20.csv"))

```

### Most popular categories/genres

```{r}

most_popular_book_categories <- dta_raw %>%
  group_by(categories) %>%
  summarize(count = n()) %>%
  mutate(percent = count / sum(count) * 100)

fig <- most_popular_book_categories %>%
  filter(!is.na(categories)) %>%
  arrange(desc(count)) %>%
  slice_max(count, n = 10) %>%
  ggplot(aes(x = count, y = reorder(categories, count))) +
  geom_col(fill = chart_color) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.1))) +
  geom_text(
    aes(label = scales::comma(count, accuracy = 1)),
    fontface = "bold",
    hjust = -.4,
    family = "Lato",
    size = 5
  ) +
  labs(
    title = "Somerville's little libraries are full of fiction",
    subtitle = "Number of books by genre in surveyed little libraries",
    x = NULL,
    y = NULL,
    caption = "Source: Open Library & Google Books APIs"
  ) +
  theme_cori_horizontal_bars()

save_plot(fig, here("export/most_popular_genres.png"), add_logo = FALSE)
save_plot(fig, here("export/most_popular_genres.svg"), add_logo = FALSE)

```


```{r}

# How much do the little libraries near the high school
# account for all the YA/Juvenile books

libraries_near_high_school <- c(
  "Ellery",
  "Trowbridge",
  "Cambridge",
  "Ellsworth"
)

ya_near_high_school <- dta_raw %>%
  filter(
    str_detect(categories, "Juvenile") | str_detect(categories, "Young Adult") 
  ) %>%
  filter(collection %in% libraries_near_high_school)

print(paste("There are ", nrow(ya_near_high_school), "YA and Juvenile books near CPLS"))

```

### Typical published date

```{r}

fig <- dta_raw %>%
  mutate(
    publish_date =  ymd(publish_date),
    publish_year = year(publish_date),
    decade = as.numeric(floor(publish_year / 10) * 10)
  ) %>%
  count(decade) %>%
  ggplot(aes(x = decade, y = n)) +
  geom_col(fill = chart_color) +
  geom_text(
    aes(label = scales::comma(n, accuracy = 1)),
    fontface = "bold",
    family = "Lato",
    size = 5,
    vjust = -.5
  ) +  
  scale_y_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .1))
  ) +
  scale_x_continuous(
    labels = scales::label_number(accuracy = 1, big.mark = ""),
    n.breaks = 7,
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    title = "Books published in the 2010s were most widespread",
    subtitle = "Number of books by publishing decade at Somerville-area little libraries",
    x = NULL,
    y = NULL,
    caption = "Source: Open Library & Google Books APIs"
  ) +
  theme_cori_horizontal_bars() +
  theme(
    axis.text.x = element_text(family = "Lato", colour = "black")
  )

save_plot(fig, here("export/books_by_decade.png"), add_logo = FALSE)
save_plot(fig, here("export/books_by_decade.svg"), add_logo = FALSE)

```

### Most common publishers

```{r}

most_common_publishers <- dta_raw %>%
  mutate(
    publisher = stringr::str_replace_all(publisher, "(?i)Books", ""),
    publisher = stringr::str_replace_all(publisher, "&amp;", "and"),
    publisher = stringr::str_replace_all(publisher, "Co\\.", "Company"),
    publisher = stringr::str_trim(publisher),
    publisher = stringr::str_to_title(publisher)
  ) %>%
  group_by(publisher) %>%
  summarize(count = n()) %>%
  mutate(percent = count / sum(count) * 100)

```

### Typical length

```{r}

fig <- ggplot(dta_raw, aes(x = length)) +
  geom_histogram(binwidth = 50, center = 25, fill = chart_color, color = "white") +
  scale_y_continuous(
    labels = scales::label_number(accuracy = 1, big.mark = ","),
    expand = expansion(mult = c(0, .1))
  ) +
  scale_x_continuous(
    labels = scales::label_number(accuracy = 1, big.mark = ""),
    n.breaks = 7,
    expand = expansion(mult = c(0, 0))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    axis.text.x = element_text(family = "Lato", colour = "black"),
    axis.ticks.length.x = unit(8, "pt"),
    axis.ticks.x = element_line(color = "#d0d2ce", linewidth = .25, linetype = "solid"),
    panel.grid.major.y = element_line(color = "#d0d2ce", linewidth = .25, linetype = "solid")
  ) +
  labs(
    title = "Books typically numbered around 300 pages",
    subtitle = "Number of books by page length, for 50 page bins",
    x = "Page length",
    y = NULL,
    caption = "Source: Open Library & Google Books APIs"
  )

save_plot(fig, here("export/page_length.png"), add_logo = FALSE)
save_plot(fig, here("export/page_length.svg"), add_logo = FALSE)


```

### What's that really long book?

```{r}


```
