---
title: "little_library_analysis"
format: html
editor: visual
---

```{r}

library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(here)
library(lubridate)
library(cori.charts)

sysfonts::font_add_google("Lato")
showtext::showtext_auto()
showtext::showtext_opts(dpi = 300)

i_am("scripts/little_library_analysis.qmd")

```

```{r}

dta_raw <- readr::read_csv(here("data/little_libraries_books_2025_06_20.csv"))

```

### Most popular categories

```{r}

most_popular_book_categories <- dta_raw %>%
  group_by(categories) %>%
  summarize(count = n()) %>%
  mutate(percent = count / sum(count) * 100)

fig <- most_popular_book_categories %>%
  filter(!is.na(categories)) %>%
  arrange(desc(count)) %>%
  slice_max(count, n = 15) %>%
  ggplot(aes(x = count, y = reorder(categories, count))) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = count), hjust = -0.1, size = 3) +
  labs(
    title = "Most popular genres",
    x = NULL,
    y = NULL
  ) +
  theme_minimal()

fig


```

### Typical published date

```{r}

fig <- dta_raw %>%
  mutate(
    publish_date =  ymd(publish_date),
    publish_year = year(publish_date),
    decade = as.numeric(floor(publish_year / 10) * 10)
  ) %>%
  count(decade) %>%
  ggplot(aes(x = decade, y = n)) +
  geom_col(fill = "steelblue") +
  scale_x_continuous(
    labels = scales::label_number(accuracy = 1, big.mark = ""),
    n.breaks = 7
  ) +
  labs(
    title = "Books Published by decade",
    x = "Year",
    y = "Number of Books"
  ) +
  theme_minimal()

fig

```

### Most common publishers

```{r}

most_common_publishers <- dta_raw %>%
  mutate(
    publisher = stringr::str_replace_all(publisher, "(?i)Books", ""),
    publisher = stringr::str_replace_all(publisher, "&amp;", "and"),
    publisher = stringr::str_replace_all(publisher, "Co\\.", "Company"),
    publisher = stringr::str_trim(publisher),
    publisher = stringr::str_to_title(publisher)
  ) %>%
  group_by(publisher) %>%
  summarize(count = n()) %>%
  mutate(percent = count / sum(count) * 100)

```

### Typical length

```{r}

fig <- ggplot(dta_raw, aes(x = length)) +
  geom_histogram(binwidth = 50, fill = "steelblue", color = "white") +
  labs(
    title = "Histogram of Book Page Lengths",
    x = "Number of Pages",
    y = "Count"
  ) +
  theme_minimal()

fig

```

### Most common subjects

```{r}

subjects_clean <- dta_raw %>%
  select(ean_isbn13, title, subjects) %>%
  separate_rows(subjects, sep = ",\\s*") %>%
  mutate(
    subjects_clean = stringr::str_replace_all(subjects, "/", " and "),
    subjects_clean = stringr::str_replace_all(subjects_clean, "&", "and"),
    subjects_clean = stringr::str_replace_all(subjects_clean, "\\.", ""),
    subjects_clean = stringr::str_replace_all(subjects_clean, "- General", "")
  ) %>%
  separate_rows(subjects_clean, sep = "\\s*--\\s*") %>%
  mutate(
    subjects_clean = stringr::str_squish(subjects_clean)
  ) %>%
  select(title, subjects_clean) %>%
  distinct()

subject_counts <- subjects_clean %>%
  group_by(subjects_clean) %>%
  summarise(
    count = n()
  )

```
